<?php

namespace Infotravel\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    public function getAvecCategorie(array $cat) {
        $req = $this->createQueryBuilder('a');
        $req->join('a.categories', 'c')
                ->where($req->expr()->in('c.nom', $cat));
        return $req->getQuery()
                        ->getResult();
    }

    public function getArticles($nombreParPage, $page) {
        $req = $this->createQueryBuilder('a')
                ->leftJoin('a.image', 'i')
                ->addSelect('i')
                ->leftJoin('a.categories', 'cat')
                ->addSelect('cat')
                ->orderBy('a.date', 'DESC')
                ->getQuery();
        $req->setFirstResult(($page - 1) * $nombreParPage)
                ->setMaxResults($nombreParPage);
        
        return new Paginator($req);
    }

}
